on:
  rss:
    url:
      - https://github.com/TiddlyWiki/TiddlyWiki5/tags.atom
    config:
      skipFirst: true
      format: |
        item.repo = new URL(item.link).pathname.split('/').slice(1,3).join('/');
        return item;
jobs:
  print-and-notify:
    name: Print and notify
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
      - name: Send notification via ntfy.sh
        env:
          title: ${{on.rss.outputs.title}}
          link: ${{on.rss.outputs.link}}
          repo: ${{on.rss.outputs.repo}}
          topicBase: ${{secrets.NTFY_TOPIC_BASE}}
        run: |
          curl \
            -X POST \
            -H "Title: $repo has new tag: $title" \
            -H "Tag: label" \
            -H "Click: $link" \
            "https://ntfy.sh/$topicBase-new-tags"
