name: Reset Actionsflow Cache
on:
  workflow_dispatch:
jobs:
  reset:
    runs-on: ubuntu-latest
    name: Reset Actionsflow Cache
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run Actionsflow Clean
        uses: actionsflow/actionsflow-action@877881186c58832926cbd76fb5674561749f7256 # v1.3.0
        with:
          args: clean
          json-secrets: ${{ toJSON(secrets) }}
