name: Reset Actionsflow Cache
on:
  workflow_dispatch:
jobs:
  reset:
    runs-on: ubuntu-latest
    name: Reset Actionsflow Cache
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run Actionsflow Clean
        uses: actionsflow/actionsflow-action@877881186c58832926cbd76fb5674561749f7256 # v1.3.0
        with:
          args: clean
          json-secrets: ${{ toJSON(secrets) }}
